config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("pwa.urls")),
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("home/", TemplateView.as_view(template_name="pages/home.html"), name="home_redir"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("", include("partneredu.users.urls")),
    path("accounts/", include("allauth.urls")),
    path("", include("django.contrib.flatpages.urls")),
    # API URLS
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

partneredu/users/urls.py
from django.urls import include, path

from partneredu.users.views import (
    AnnouncementDetailView,
    AnnouncementListView,
    DashboardView,
    EventDetailView,
    EventListView,
    MapView,
    OrganizationDetailView,
    OrganizationListView,
    UserDetailView,
    UserRedirectView,
    UserUpdateView,
    join_event,
    join_organization,
    leave_event,
    leave_organization,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=UserRedirectView.as_view(), name="redirect"),
    path("~update/", view=UserUpdateView.as_view(), name="update"),
    path("users/<int:pk>/", view=UserDetailView.as_view(), name="detail"),
    path("dashboard", view=DashboardView.as_view(), name="dashboard"),
    path("events/", view=EventListView.as_view(), name="event_list"),
    path("events/<int:pk>/", view=EventDetailView.as_view(), name="event_detail"),
    path("organizations/", view=OrganizationListView.as_view(), name="organization_list"),
    path("organizations/<int:id>/", view=OrganizationDetailView.as_view(), name="organization_detail"),
    path("recent/", view=AnnouncementListView.as_view(), name="announcement_list"),
    path("announcement/<slug:slug>/", view=AnnouncementDetailView.as_view(), name="announcement_detail"),
    path("map", view=MapView.as_view(), name="map"),
    path("event/join/<int:pk>/", view=join_event, name="event_join"),
    path("event/leave/<int:pk>/", view=leave_event, name="event_leave"),
    path("organization/subscribe/<int:pk>/", view=join_organization, name="organization_subscribe"),
    path("organization/unsubscribe/<int:pk>/", view=leave_organization, name="organization_unsubscribe"),
    path("api/", include("partneredu.users.api_views")),
]

partneredu/users/forms.py
from os import environ
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core import validators
from django.forms import CharField, EmailField, Field, MultipleChoiceField, forms
from django.utils.translation import gettext_lazy as _
from partneredu.users.models import Tag
from partneredu.users.utils.choices import ORGANIZATION_TYPES
User = get_user_model()


class MinLengthValidator(validators.MinLengthValidator):
    message = "Ensure this value has at least %(limit_value)d elements (it has %(show_value)d)."


class MaxLengthValidator(validators.MaxLengthValidator):
    message = "Ensure this value has at most %(limit_value)d elements (it has %(show_value)d)."


class CommaSeparatedCharField(Field):
    def __init__(self, dedup=True, max_length=None, min_length=None, *args, **kwargs):
        self.dedup, self.max_length, self.min_length = dedup, max_length, min_length
        super().__init__(*args, **kwargs)
        if min_length is not None:
            self.validators.append(MinLengthValidator(min_length))
        if max_length is not None:
            self.validators.append(MaxLengthValidator(max_length))

    def to_python(self, value):
        if value in validators.EMPTY_VALUES:
            return []

        value = [item.strip() for item in value.split(",") if item.strip()]
        if self.dedup:
            value = list(set(value))

        return value

    def clean(self, value):
        value = self.to_python(value)
        self.validate(value)
        self.run_validators(value)
        return value


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

class EventSearchForm(forms.Form):
    name = CharField(label="Event Name", required=False)
    keywords = CharField(label="Keywords to search for", required=False)
    if environ.get("DJANGO_SETTINGS_MODULE") == "config.settings.test": # used so tests/compile messages works without db 
            tags = MultipleChoiceField(label="Tags to filter by", choices=[("example", "tag")], required=False)
    else:
        tags = MultipleChoiceField(label="Tags to filter by", choices=Tag.objects.values_list("name", "name"), required=False)

class OrganizationSearchForm(forms.Form):
    name = CharField(label="Organization Name", max_length=100, required=False)
    category = MultipleChoiceField(
        label="Organization type", choices=[(i, i) for i in ORGANIZATION_TYPES], required=False
    )
    keywords = CommaSeparatedCharField(label="Keywords", max_length=100, required=False)
    # if settings.DEBUG is False:
    #     location = PlainLocationField(label="Location", required=False)
    #     radius = FloatField(label="Radius (in km)", required=False, max_value=1000, min_value=0.1)
    # else:
    location = CharField(label="Location", required=False)

    def clean(self):
        # if settings.DEBUG is False:
        #     location = self.cleaned_data.get("location")
        #     radius = self.cleaned_data.get("radius")
        #     if location and not radius:
        #         raise ValidationError("Please provide a radius.")
        return self.cleaned_data

partneredu/users/views.py
import json

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Case, F, IntegerField, Q, When
# from django.db.models.functions import Extract
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

import partneredu
from partneredu.users.forms import OrganizationSearchForm,EventSearchForm
from partneredu.users.models import Announcement, Event, Organization

# if settings.DEBUG is False:
#     from django.contrib.gis.db.models.functions import Distance
#     from django.contrib.gis.geos import fromstr
#     from django.contrib.gis.measure import D

# Get the user model from Django's built-in user model
User = get_user_model()


class MessageDetailView(DetailView):
    def get(self, request, *args, **kwargs):
        """
        This method handles the GET request.
        """
        if "msg" in request.session and request.session["msg"] is not None:
            if "msg_err" in request.session:
                del request.session["msg_err"]
                messages.warning(request, request.session["msg"])
            else:
                messages.success(request, request.session["msg"])
            del request.session["msg"]

        return super().get(request, *args, **kwargs)


class UserDetailView(LoginRequiredMixin, DetailView):
    """
    This view is for displaying the details of a user.
    It requires the user to be logged in to view their details.
    """

    model = User  # The model being used is the User model
    slug_field = "id"  # The field in the User model that's used for the lookup is 'id'
    slug_url_kwarg = "id"  # The name of the keyword argument in the URLconf is 'id'


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    This view is for updating the details of a user.
    It requires the user to be logged in to update their details.
    Upon successful update, a success message is displayed.
    """

    model = User  # The model being used is the User model
    fields = ["name"]  # The field that can be updated is 'name'
    success_message = _("Information successfully updated")  # The message displayed upon successful update

    def get_success_url(self):
        """
        This method returns the URL to redirect to after the user's details are successfully updated.
        """
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()  # The URL to redirect to is the user's detail view

    def get_object(self):
        """
        This method returns the User object to be updated.
        """
        return self.request.user  # The User object to be updated is the currently logged in user


class UserRedirectView(LoginRequiredMixin, RedirectView):
    """
    This view is for redirecting the user to their detail view.
    It requires the user to be logged in to be redirected.
    """

    permanent = False  # This is not a permanent redirect

    def get_redirect_url(self):
        """
        This method returns the URL to redirect to.
        """
        return reverse(
            "users:detail", kwargs={"pk": self.request.user.pk}
        )  # The URL to redirect to is the user's detail view


class EventListView(ListView):
    """
    This view is for displaying a list of events.
    """

    model = Event  # The model being used is the Event model
    template_name = "events/list.html"  # The template used for this view is 'event_list.html'
    context_object_name = "events"  # The name of the variable to be used in the template context is 'events'
    paginate_by = 10  # The number of events displayed per page is 10
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = EventSearchForm()
        return context
    
    def get_queryset(self):
        """
        This method returns the queryset to be used for the list view.
        """
        if self.request.GET.get("attendance", None) is not None:
            return Event.objects.all().order_by("-attendees__count")
        now = timezone.now()  # Get the current time
        object_list = Event.objects.all() 
    #     Event.objects.annotate(
    #     relevance=Case(
    #         When(start_date__lte=now, end_date__gte=now, then=1),
    #         When(start_date__gt=now, then=2),
    #         When(end_date__lt=now, then=3),
    #         output_field=IntegerField(),
    #     )
    # )
    # .annotate(
    #     timediff=Case(
    #         When(start_date__gt=now, then=Extract(F("start_date") - now, 'seconds')),
    #         When(end_date__lt=now, then=Extract(now - F("end_date"), 'seconds')),
    #         default=0,
    #         output_field=IntegerField(),
    #     )
    # )
    # .order_by("relevance", "timediff")
    #     )       
        form = EventSearchForm(self.request.GET)

        if form.is_valid():
            name = form.cleaned_data.get("name")
            tags = form.cleaned_data.get("tags")
            keywords = form.cleaned_data.get("keywords")

            if name:
                object_list = object_list.filter(Q(name__icontains=name) | Q(info__icontains=name))

            if keywords:
                for keyword in keywords:
                    object_list = object_list.filter(description__icontains=keyword)
            if tags: 
                object_list = object_list.filter(tags__in=[tags])

        return object_list
    
class EventDetailView(MessageDetailView): 
    """
    This view is for displaying the details of an event.
    """

    model = Event  # The model being used is the Event model
    template_name = "events/detail.html"  # The template used for this view is 'event_detail.html'

    def get_object(self, queryset=None):
        """
        This method returns the Event object to be shown in detail view.
        """
        id_ = self.kwargs.get("pk")  # Get the primary key from the URL
        return get_object_or_404(Event, id=id_)  # Return the Event object with the given primary key


class OrganizationListView(ListView):
    """
    This view is for displaying a list of organizations.
    """

    model = Organization  # The model being used is the Organization model
    template_name = "organizations/list.html"  # The template used for this view is 'organization_list.html'
    context_object_name = (
        "organizations"  # The name of the variable to be used in the template context is 'organizations'
    )
    paginate_by = 10  # The number of organizations displayed per page is 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = OrganizationSearchForm()
        return context

    def get_queryset(self):
        form = OrganizationSearchForm(self.request.GET)
        object_list = self.model.objects.all().order_by("-subscribers")

        if form.is_valid():
            name = form.cleaned_data.get("name")
            category = form.cleaned_data.get("category")
            keywords = form.cleaned_data.get("keywords")
            location = form.cleaned_data.get("location")
            # radius = form.cleaned_data.get("radius")

            if name:
                object_list = object_list.filter(Q(name__icontains=name) | Q(description__icontains=name))

            if category:
                object_list = object_list.filter(category__in=category)
            if keywords:
                for keyword in keywords:
                    object_list = object_list.filter(description__icontains=keyword)
            if location:
                # if settings.DEBUG is False:
                #     lat, lon = location
                #     user_location = fromstr(f"POINT({lon} {lat})", srid=4326)
                #     object_list = object_list.annotate(distance=Distance("location", user_location)).filter(
                #         distance__lte=D(km=radius)
                #     )
                # else:
                object_list = object_list.filter(description__icontains=location)

        return object_list


class OrganizationDetailView(MessageDetailView):
    """
    This view is for displaying the details of an organization.
    """

    model = Organization  # The model being used is the Organization model
    template_name = "organizations/detail.html"  # The template used for this view is 'organization_detail.html'

    def get_object(self, queryset=None):
        """
        This method returns the Organization object to be shown in detail view.
        """
        pk_ = self.kwargs.get("id")  # Get the slug from the URL
        return get_object_or_404(Organization, id=pk_)  # Return the Organization object with the given ID


class AnnouncementListView(ListView):
    """
    This view is for displaying a list of announcements.
    """

    model = Event  # The model being used is the Event model
    template_name = "announcements/list.html"  # The template used for this view is 'announcement_list.html'
    context_object_name = (
        "announcements"  # The name of the variable to be used in the template context is 'announcements'
    )
    paginate_by = 10  # The number of announcements displayed per page is 10

    def get_queryset(self):
        """
        This method returns the queryset to be used for the list view.
        """
        return Announcement.objects.filter(date_posted__lte=timezone.now()).order_by(
            "-date_posted"
        )  # Return all Announcement objects that were posted before the current time, \

partneredu/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}
  Forbidden (403)
{% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

partneredu/templates/base.html
{% load static pwa i18n compress %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    {% progressive_web_app_meta %}
    <title>
      {% block title %}
        PartnerEDU
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="A CMS for schools" />
    <meta name="author" content="Jason Cameron, Chelsea Wong, Nirvan Rabbani" />
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    {% block css %}
      <!-- Latest compiled and minified Bootstrap CSS -->
      <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
            integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer" />
      <!-- Your stuff: Third-party CSS libraries go here -->
      <!-- This file stores project-specific CSS -->
      {% compress css %}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="{% static 'css/fonts.css' %}" rel="stylesheet">
        <link href="{% static 'css/project.css' %}" rel="stylesheet" />
      {% endcompress %}
    {% endblock css %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS -->
      <script defer
              src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
              integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
              crossorigin="anonymous"
              referrerpolicy="no-referrer"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->
      <!-- place project specific Javascript in this file -->
      {% compress js %}
        <script defer src="{% static 'js/project.js' %}"></script>
      {% endcompress %}
    {% endblock javascript %}
  {% block deps %}
  {% endblock deps %}
  </head>
  <body>
    <div class="mb-1">
      <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler navbar-toggler-right"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">PartnerEDU</a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:dashboard' %}">{% translate "dashboard" %} <span class="visually-hidden">(current)</span></a>
              </li>
              <!--<li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>-->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:event_list' %}">{% translate "events" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:organization_list' %}">{% translate "organizations" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:announcement_list' %}">{% translate "announcements" %}</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.pk %}">{% translate "my profile" %}</a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" href="{% url 'account_logout' %}">{% translate "log out" %}</a>
                </li>
              {% else %}
                {% if ACCOUNT_ALLOW_REGISTRATION %}
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "register" %}</a>
                  </li>
                {% endif %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "log in" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="container body-content" style="margin-top: 5%;">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button"
                    class="btn-close"
                    data-bs-dismiss="alert"
                    aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}
        <!-- <p>Chippi chippi chappa chappa</p> -->
      {% endblock content %}
    </div>
    <!-- /container -->
    {% block modal %}
    {% endblock modal %}
    {% block inline_javascript %}
      {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
      {% endcomment %}
    {% endblock inline_javascript %}
  </body>
</html>

partneredu/templates/dashboard.html
{% extends "base.html" %}

{% load compress static %}

{% block title %}
  Stravos: Dashboard
{% endblock title %}
{% block content %}
  <!-- djlint:off -->
{% compress js %}
  <script defer>
    const url = '/api/distance/';
    navigator.geolocation.getCurrentPosition(function(position) {
        const user_latitude = position.coords.latitude;
        const user_longitude = position.coords.longitude;
        console.log('User latitude: ' + user_latitude);
        {% for event in events %}
        // Call the Django view that uses the `calculate_distance` template tag here.
          let event_latitude = "{{ event.location }}".split(",")[0];
          let event_longitude = "{{ event.location }}".split(",")[1];
          // Define the URL of the Django view
          // Prepare the data to be sent in the request
          let data = {
            'user_latitude': user_latitude,
            'user_longitude': user_longitude,
            'event_latitude': event_latitude,
            'event_longitude': event_longitude
          };

          // Define the options for the fetch request
          let options = {
            method: 'POST', // Adjust the method if necessary
            headers: {
              'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
          };

          // Make the fetch request
          fetch(url, options)
            .then(response => response.json())
            .then(data => {
              // Display the calculated distance on the page
              document.getElementById('distance-' + {{ event.id }}).textContent = parseFloat(data.distance).toFixed(3) + ' KM';
            })
            .catch(error => {
              console.error('Error:', error);
            });

        {% endfor %}
      });
  </script>
              {% endcompress %}
  <!-- djlint:on -->
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Dashboard</h1>
        <p>
          Welcome to the PartnerEDU dashboard!
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h2>Recent Activities</h2>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Date</th>
              <th>Activity</th>
              <th>Distance</th>
            </tr>
          </thead>
          <tbody>
            {% for event in events.all %}
              <tr>
                <td>{{ event.start_date|date:'d/m' }} - {{ event.end_date|date:'d/m' }}</td>
                <td>{{ event.name }}</td>
                <td id="distance-{{ event.id }}">calculating...</td>
                {% comment %}Calculating gets replaced by the real location{% endcomment %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}